services:
  ceres:
    build: .
    container_name: neocron-server
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ./ceres.docker.cfg:/app/ceres.cfg:ro
      - ./data/database:/app/database
      - ${NC2_CLIENT_PATH:-/home/javier/Neocron2}:/client:ro
    restart: unless-stopped
