package server.gameserver.packets;

import static org.junit.Assert.*;

import java.lang.reflect.Method;

import org.junit.Test;

import server.gameserver.packets.client_udp.ReliableAckSubPacket;
import server.gameserver.packets.client_udp.Sub0x00Recognized;
import server.gameserver.packets.client_udp.Sub0x06Recognized;
import server.gameserver.packets.client_udp.Sub0x07Recognized;
import server.gameserver.packets.client_udp.Sub0x0DRecognized;
import server.gameserver.packets.client_udp.Sub0x0FRecognized;
import server.gameserver.packets.client_udp.Sub0x11Recognized;
import server.gameserver.packets.client_udp.Sub0x31Recognized;
import server.gameserver.packets.client_udp.UnknownClientUDPPacket;
import server.interfaces.GameServerEvent;

/**
 * Pins the catalog-driven recognition added for task #137. Each
 * test feeds the dispatcher one of the documented retail-capture
 * byte patterns and asserts that:
 *
 * <ol>
 *   <li>The dispatcher returns a typed packet (not an
 *       {@link UnknownClientUDPPacket} fall-through).</li>
 *   <li>{@code execute()} is a no-op — these are recognise-only
 *       handlers until structure is verified at full-precision.</li>
 * </ol>
 *
 * <p>Sample bytes are pulled from
 * {@code docs/protocol/_data/packets.json} (auto-generated by
 * {@code tools/catalog_extract.py} from the retail pcap corpus).
 * The exact hex strings appear in commit messages so future
 * regenerations of the catalog can re-verify the pin.
 */
public class GamePacketReaderUDPCatalogRecognitionTest {

    private static byte[] hex(String h) {
        h = h.replaceAll("\\s+", "");
        byte[] b = new byte[h.length() / 2];
        for (int i = 0; i < b.length; i++) {
            b[i] = (byte) Integer.parseInt(h.substring(i * 2, i * 2 + 2), 16);
        }
        return b;
    }

    private static GameServerEvent decode(byte[] subPacket) throws Exception {
        Method m = GamePacketReaderUDP.class.getDeclaredMethod(
                "decodesub13", byte[].class);
        m.setAccessible(true);
        return (GameServerEvent) m.invoke(null, (Object) subPacket);
    }

    // ─── 0x00 — multi-variant status broadcast family ─────────────

    @Test
    public void recognises0x00TwelveByteVariant() throws Exception {
        // From RETAIL_AUGUSTO: 00 3c 01 00 02 c0 4a 00 00 e1 28 00
        GameServerEvent ev = decode(hex("003c010002c04a0000e12800"));
        assertNotNull("0x00 must produce a typed event", ev);
        assertTrue("expected Sub0x00Recognized, got "
                + ev.getClass().getName(),
                ev instanceof Sub0x00Recognized);
        assertFalse("must not fall through to Unknown",
                ev instanceof UnknownClientUDPPacket);
    }

    @Test
    public void recognises0x00SixByteVariant() throws Exception {
        // From RETAIL_FULL_PCAP_TRACE: 00 2d 00 64 01 00
        GameServerEvent ev = decode(hex("002d00640100"));
        assertTrue(ev instanceof Sub0x00Recognized);
    }

    @Test
    public void recognises0x00FourByteVariant() throws Exception {
        // From RETAIL_HANNIBAL: 00 00 09 00
        GameServerEvent ev = decode(hex("00000900"));
        assertTrue(ev instanceof Sub0x00Recognized);
    }

    // ─── 0x01 — 3-byte reliable-ACK frame ─────────────────────────

    @Test
    public void recognises0x01AckFrame() throws Exception {
        // From RETAIL_VEHICLE_DRONE: 01 44 5a (LE16 seq=0x5a44).
        GameServerEvent ev = decode(hex("01445a"));
        assertTrue("expected ReliableAckSubPacket, got "
                + ev.getClass().getName(),
                ev instanceof ReliableAckSubPacket);
        assertEquals("LE16 seq must decode as 0x5a44",
                0x5a44, ((ReliableAckSubPacket) ev).ackSeq());
    }

    @Test
    public void recognises0x01MonotonicSequence() throws Exception {
        // Three consecutive samples from the same capture confirm
        // the LE16 layout: 01 44 5a, 01 45 5a, 01 46 5a.
        ReliableAckSubPacket a = (ReliableAckSubPacket) decode(hex("01445a"));
        ReliableAckSubPacket b = (ReliableAckSubPacket) decode(hex("01455a"));
        ReliableAckSubPacket c = (ReliableAckSubPacket) decode(hex("01465a"));
        assertEquals(0x5a44, a.ackSeq());
        assertEquals(0x5a45, b.ackSeq());
        assertEquals(0x5a46, c.ackSeq());
    }

    // ─── 0x06 — 1-byte singleton ──────────────────────────────────

    @Test
    public void recognises0x06Singleton() throws Exception {
        GameServerEvent ev = decode(hex("06"));
        assertTrue(ev instanceof Sub0x06Recognized);
    }

    // ─── 0x07 — 10-byte reliable-shaped (single-capture) ──────────

    @Test
    public void recognises0x07ReliableWrapper() throws Exception {
        // From RETAIL_VEHICLE_DRONE: 07 00 03 fc 00 1f 01 00 4a 3a
        GameServerEvent ev = decode(hex("070003fc001f01004a3a"));
        assertTrue(ev instanceof Sub0x07Recognized);
    }

    // ─── 0x0d — 10-byte reliable-shaped (2 captures) ──────────────

    @Test
    public void recognises0x0DReliableWrapper() throws Exception {
        // From RETAIL_ZONING_AND_ITEMS_LONG: 0d 00 03 74 03 1f 01 00 2d 05
        GameServerEvent ev = decode(hex("0d000374031f01002d05"));
        assertTrue(ev instanceof Sub0x0DRecognized);
    }

    // ─── 0x0f — 10-byte reliable-shaped (5 captures) ──────────────

    @Test
    public void recognises0x0FReliableWrapper38() throws Exception {
        // Most common 0x0f variant: tail = 38 04
        // From RETAIL_FULL_PCAP_TRACE: 0f 00 03 fe 00 1f 01 00 38 04
        GameServerEvent ev = decode(hex("0f0003fe001f01003804"));
        assertTrue(ev instanceof Sub0x0FRecognized);
    }

    @Test
    public void recognises0x0FReliable1bAlt() throws Exception {
        // Alternate 0x0f variant: reliable type 0x1b
        // From RETAIL_CREATION_LEVELING: 0f 00 03 26 03 1b 82 00 00 00
        GameServerEvent ev = decode(hex("0f000326031b82000000"));
        assertTrue(ev instanceof Sub0x0FRecognized);
    }

    // ─── 0x11 — 10-byte reliable-shaped (2 captures) ──────────────

    @Test
    public void recognises0x11ReliableWrapper() throws Exception {
        // From RETAIL_ZONING_AND_ITEMS_LONG: 11 00 03 6e 02 1f 01 00 38 01
        GameServerEvent ev = decode(hex("1100036e021f01003801"));
        assertTrue(ev instanceof Sub0x11Recognized);
    }

    // ─── 0x31 — 1-byte singleton (1 capture) ──────────────────────

    @Test
    public void recognises0x31Singleton() throws Exception {
        GameServerEvent ev = decode(hex("31"));
        assertTrue(ev instanceof Sub0x31Recognized);
    }

    // ─── Negative tests — unrelated bytes still fall to Unknown ───

    @Test
    public void unrelatedTopByteStillUnknown() throws Exception {
        // 0x77 is not in the catalog and not in the dispatch table —
        // must still fall to Unknown.
        GameServerEvent ev = decode(hex("77000000"));
        assertNotNull(ev);
        assertTrue("expected Unknown, got " + ev.getClass().getName(),
                ev instanceof UnknownClientUDPPacket);
    }

    @Test
    public void executeIsNoopAcrossAllNewTypes() throws Exception {
        // None of the recognise-only packets must throw on
        // execute() with a null Player — they're pure no-ops.
        // Cast disambiguates the GamePacketDecoderUDP overload set
        // (execute(Player) vs execute(GameServerTCPConnection)).
        server.gameserver.Player nullPl = null;
        new Sub0x00Recognized(hex("003c010002c04a0000e12800")).execute(nullPl);
        new ReliableAckSubPacket(hex("01445a")).execute(nullPl);
        new Sub0x06Recognized(hex("06")).execute(nullPl);
        new Sub0x07Recognized(hex("070003fc001f01004a3a")).execute(nullPl);
        new Sub0x0DRecognized(hex("0d000374031f01002d05")).execute(nullPl);
        new Sub0x0FRecognized(hex("0f0003fe001f01003804")).execute(nullPl);
        new Sub0x11Recognized(hex("1100036e021f01003801")).execute(nullPl);
        new Sub0x31Recognized(hex("31")).execute(nullPl);
    }

    @Test
    public void ackSeqOnTooShortBufferIsNegative() {
        // Defensive: ackSeq() must not blow up on a malformed
        // 1-byte 0x01 frame.
        assertEquals(-1, new ReliableAckSubPacket(hex("01")).ackSeq());
    }
}
