#!/usr/bin/env python3
"""Constants audit linter — keeps every "CONSTANT" field in the packet
catalog classified, and guards against Ceres-J freezing an unverified
variable as a literal (the `0x03/0x28` per-NPC-handle bug class).

Background: a wire constant is only legitimate if it is a tag/opcode/
discriminator, compiler padding, a reserved/version field, or a fixed
record-size. Anything else flagged "constant" is most likely an
undersampled variable (corpus bias). See docs/protocol/CONSTANTS_AUDIT.md
and the `feedback_constants_are_suspect` memory.

Single source of truth: docs/protocol/_data/constants.json — one entry
per constant field, keyed by (packet_doc, normalized line text), tagged
with a `kind`:

    discriminator  opcode / sub-opcode / sub-tag / variant marker / length
    padding        compiler alignment / inter-field zero pad
    reserved       reserved / unused / zeroed pointer or future field
    magic          version / handshake magic (genuinely hardcoded client-side)
    recordsize     fixed struct stride / record-size field
    verified       proven invariant by experiment (e.g. char_count hard-cap 4)
    UNVERIFIED     looks constant only in the corpus — must be ECHOED by
                   Ceres-J from the source record, NEVER hardcoded

Modes:
    --scan     re-scan packet docs, merge newly-found constant lines into
               the manifest (auto-kind for new ones; never clobbers an
               existing manual kind), write manifest back.
    --inject   (re)write a kind-tagged `## Constants (catalog-audit)` table
               into each packet doc between <!-- constants-audit --> markers.
    --check    CI gate (default). Exit non-zero if any constant line in a
               packet doc is unclassified, any kind is invalid, or an
               UNVERIFIED field appears hardcoded in its Ceres-J emitter.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PKT_DIR = HERE.parent / "docs" / "protocol" / "packets"
MANIFEST = HERE.parent / "docs" / "protocol" / "_data" / "constants.json"
EMITTER_DIR = HERE.parent / "src" / "main" / "java" / "server" / "gameserver" / "packets" / "server_tcp"

VALID_KINDS = {
    "discriminator", "padding", "reserved", "magic", "recordsize",
    "verified", "UNVERIFIED",
}

BEGIN = "<!-- constants-audit (generated by tools/constants_audit.py --inject; edit kinds in _data/constants.json) -->"
END = "<!-- /constants-audit -->"

# A line inside a fenced code block is a "constant declaration" if it
# carries an offset token AND a constant keyword.
KEYWORD = re.compile(
    r"\bCONSTANT\b|constant|padding|\bpad\b|reserved|unused|"
    r"always 0x|always zero|separator|placeholder|\bmagic\b",
    re.IGNORECASE,
)
OFFSET = re.compile(r"^\s*(\[\s*\d|\d+\s+\d+\s)")


def norm(line: str) -> str:
    """Normalize a constant line for use as a stable manifest key."""
    return re.sub(r"\s+", " ", line.strip())


def auto_kind(text: str) -> str:
    """First-pass classifier for a freshly-discovered constant line."""
    t = text.lower()
    if re.search(r"opcode|sub-opcode|sub-tag|discriminator|inner opcode"
                 r"|variant marker|marker b|length|chain_key|envelope flag", t):
        return "discriminator"
    if "char_count" in t or "number of chars" in t or "slot-array" in t:
        return "verified"
    if re.search(r"struct_size|record|charstructure|stride|record-size", t):
        return "recordsize"
    if re.search(r"padding|\bpad\b|zero pad|alignment|separator", t):
        return "padding"
    if re.search(r"reserved|unused", t):
        return "reserved"
    if re.search(r"magic|version|handshake.*('|ascii)|'f'|'h'|'x'", t):
        return "magic"
    # Everything left that was flagged "constant" is suspect by default.
    return "UNVERIFIED"


def find_constant_lines(md: str) -> list[str]:
    """Return normalized constant-declaration lines inside fenced code
    blocks of a packet doc."""
    out, in_fence = [], False
    for raw in md.splitlines():
        if raw.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if not in_fence:
            continue
        if OFFSET.match(raw) and KEYWORD.search(raw):
            out.append(norm(raw))
    return out


def load_manifest() -> dict:
    if MANIFEST.exists():
        return json.loads(MANIFEST.read_text())
    return {"_doc": "kind per constant field; see tools/constants_audit.py",
            "entries": []}


def save_manifest(m: dict) -> None:
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(m, indent=2, ensure_ascii=False) + "\n")


def emitter_for(doc: Path, md: str) -> Path | None:
    """Best-effort packet-doc -> Ceres-J emitter Java file."""
    m = re.search(r"server\.gameserver\.packets\.server_tcp\.(\w+)", md)
    if m:
        f = EMITTER_DIR / f"{m.group(1)}.java"
        if f.exists():
            return f
    return None


def cmd_scan() -> int:
    m = load_manifest()
    by_key = {(e["packet"], e["line"]): e for e in m["entries"]}
    added = 0
    for doc in sorted(PKT_DIR.glob("*.md")):
        if doc.name == "INDEX.md":
            continue
        for line in find_constant_lines(doc.read_text()):
            key = (doc.name, line)
            if key not in by_key:
                e = {"packet": doc.name, "line": line,
                     "kind": auto_kind(line), "note": ""}
                by_key[key] = e
                added += 1
    m["entries"] = sorted(by_key.values(), key=lambda e: (e["packet"], e["line"]))
    save_manifest(m)
    print(f"scan: manifest now {len(m['entries'])} entries (+{added} new)")
    kinds: dict[str, int] = {}
    for e in m["entries"]:
        kinds[e["kind"]] = kinds.get(e["kind"], 0) + 1
    for k in sorted(kinds):
        print(f"  {k:14} {kinds[k]}")
    return 0


def cmd_inject() -> int:
    m = load_manifest()
    per_doc: dict[str, list] = {}
    for e in m["entries"]:
        per_doc.setdefault(e["packet"], []).append(e)
    n = 0
    for doc in sorted(PKT_DIR.glob("*.md")):
        entries = per_doc.get(doc.name)
        if not entries:
            continue
        rows = ["| Field | kind | note |", "|---|---|---|"]
        for e in sorted(entries, key=lambda e: e["line"]):
            field = e["line"].replace("|", "\\|")
            rows.append(f"| `{field}` | {e['kind']} | {e.get('note', '')} |")
        block = (f"{BEGIN}\n## Constants (catalog-audit)\n\n"
                 + "\n".join(rows) + f"\n{END}\n")
        md = doc.read_text()
        if BEGIN in md and END in md:
            md = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
                        block, md, flags=re.DOTALL)
        else:
            md = md.rstrip() + "\n\n" + block
        doc.write_text(md)
        n += 1
    print(f"inject: wrote kind-tagged tables into {n} docs")
    return 0


def cmd_check() -> int:
    m = load_manifest()
    by_key = {(e["packet"], e["line"]): e for e in m["entries"]}
    errors, warnings = [], []

    # 1. valid kinds
    for e in m["entries"]:
        if e["kind"] not in VALID_KINDS:
            errors.append(f"{e['packet']}: invalid kind '{e['kind']}' "
                          f"for `{e['line']}`")

    # 2. every constant line in every doc is classified
    for doc in sorted(PKT_DIR.glob("*.md")):
        if doc.name == "INDEX.md":
            continue
        for line in find_constant_lines(doc.read_text()):
            if (doc.name, line) not in by_key:
                errors.append(f"{doc.name}: UNCLASSIFIED constant — add to "
                              f"_data/constants.json: `{line}`")

    # 3. UNVERIFIED fields must not be hardcoded in the Ceres-J emitter
    unverified = [e for e in m["entries"] if e["kind"] == "UNVERIFIED"]
    for e in unverified:
        doc = PKT_DIR / e["packet"]
        emitter = emitter_for(doc, doc.read_text()) if doc.exists() else None
        if not emitter:
            continue
        # heuristic: pull hex byte values from the line (after dropping
        # the leading offset token so `[25..29]` isn't read as bytes),
        # look for a matching hardcoded literal in the emitter. Skip
        # 0x00 — zeros are ubiquitous and usually legit padding.
        rem = re.sub(r"^\s*(\[[^\]]*\]|\d+\s+\d+)\s*", "", e["line"])
        hexes = [h for h in re.findall(r"0x([0-9a-fA-F]{2})\b|\b([0-9a-fA-F]{2})\b", rem)]
        hexes = [a or b for a, b in hexes]
        src = emitter.read_text()
        for h in hexes:
            if h.lower() == "00":
                continue
            if re.search(rf"0x{h}\b|write\(\s*{int(h, 16)}\s*\)", src):
                warnings.append(
                    f"{e['packet']}: UNVERIFIED `{e['line']}` — value "
                    f"0x{h} appears hardcoded in {emitter.name}; confirm "
                    f"it is ECHOED from the record, not frozen")
                break

    print(f"check: {len(m['entries'])} classified constants, "
          f"{len(unverified)} UNVERIFIED")
    for w in warnings:
        print(f"  WARN  {w}")
    if unverified:
        print("\n  UNVERIFIED inventory (must be echoed, never hardcoded):")
        for e in unverified:
            print(f"    - {e['packet']}: {e['line']}")
    if errors:
        print(f"\nFAIL ({len(errors)} error(s)):", file=sys.stderr)
        for er in errors:
            print(f"  {er}", file=sys.stderr)
        return 1
    print("\nOK — every catalog constant is classified.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--scan", action="store_true", help="merge new constant lines into the manifest")
    g.add_argument("--inject", action="store_true", help="write kind-tagged tables into packet docs")
    g.add_argument("--check", action="store_true", help="CI gate (default)")
    a = ap.parse_args()
    if a.scan:
        return cmd_scan()
    if a.inject:
        return cmd_inject()
    return cmd_check()


if __name__ == "__main__":
    sys.exit(main())
