#!/usr/bin/env python3
"""opcode_analysis.py — extract structural patterns from the
observed-opcode catalog.

Loads docs/protocol/_data/packets.json and surfaces:

1. TCP opcode space organized by high byte (subsystem)
2. UDP raw-outer / reliable-sub opcode space side-by-side so we
   can verify whether 0x03/0xNN really mirrors raw 0xNN
3. Size statistics per opcode (fixed-size vs variable; small
   constants vs large variable bodies)
4. Direction patterns within each opcode group
5. Co-occurrence: which opcodes appear together inside the same
   UDP datagram (= same 0x13 wrapper)

Output: docs/protocol/OPCODE_STRUCTURE.md.
"""
from __future__ import annotations
import json, sys
from pathlib import Path
from collections import defaultdict, Counter


def load_data():
    p = Path("docs/protocol/_data/packets.json")
    if not p.exists():
        sys.exit("missing _data/packets.json — run catalog_extract first")
    return json.loads(p.read_text())


def parse_key(k: str):
    """`UDP S->C 0x03/0x07/0x01` → (transport, dir, [outer, sub, disc])"""
    parts = k.split()
    transport = parts[0]
    direction = parts[1]
    bits = parts[2].split("/")
    nums = [int(b, 16) for b in bits]
    return transport, direction, nums


# ─── TCP analysis ─────────────────────────────────────────────────────

def analyze_tcp(packets):
    by_op = {}
    for k, e in packets.items():
        t, d, nums = parse_key(k)
        if t != "TCP": continue
        op = nums[0]
        by_op[op] = by_op.get(op, [])
        by_op[op].append((d, k, e))

    # Group by high byte (= subsystem)
    by_hi = defaultdict(list)
    for op, entries in by_op.items():
        by_hi[op >> 8].append((op, entries))

    return by_hi


# ─── UDP analysis ─────────────────────────────────────────────────────

def analyze_udp(packets):
    """Build:
    - raw[opcode][dir] = entry  (raw outer)
    - reliable[opcode][dir] = entry  (after 0x03 wrapper)
    - multipart[(disc)][dir] = entry  (after 0x03/0x07 wrapper)
    """
    raw = defaultdict(dict)
    reliable = defaultdict(dict)
    multipart = defaultdict(dict)
    for k, e in packets.items():
        t, d, nums = parse_key(k)
        if t != "UDP": continue
        if len(nums) == 1:
            raw[nums[0]][d] = (k, e)
        elif len(nums) == 2:
            outer, sub = nums
            if outer == 0x03:
                reliable[sub][d] = (k, e)
            else:
                # outer != 0x03 (rare) — log as raw of outer with a sub
                raw[outer][d] = (k, e)
        elif len(nums) == 3:
            outer, sub, disc = nums
            multipart[disc][d] = (k, e)
    return raw, reliable, multipart


# ─── Output ───────────────────────────────────────────────────────────

def fmt_size(e):
    return f"{e['size_min']}/{e['size_avg']}/{e['size_max']}"


def fmt_count(e):
    n = e.get("count", 0)
    cap = len(e.get("captures", {}))
    return f"{n} obs · {cap} cap"


def fixed_size(e):
    return e["size_min"] == e["size_max"]


def write_report(packets, captures, out_path):
    by_hi = analyze_tcp(packets)
    raw, reliable, multipart = analyze_udp(packets)

    lines = []
    lines.append("# Opcode Structure Analysis\n\n")
    lines.append("_Auto-generated by `tools/opcode_analysis.py` "
                 f"from {len(packets)} cataloged packet types across "
                 f"{len(captures)} retail captures._\n\n")

    # ─── TCP ───────────────────────────────────────────────────────
    lines.append("## TCP opcode space\n\n")
    lines.append("TCP opcodes are 16-bit big-endian. The **high byte**"
                 " segments the subsystem; the low byte selects the "
                 "operation within that subsystem. Convention "
                 "observed:\n\n")

    HIGH_BYTE_NAMES = {
        0x80: "Connection handshake (3-way)",
        0x83: "Game session state (server-driven)",
        0x84: "Account / character (client-driven)",
        0x87: "Gamedata / config sync",
        0xa0: "Session-ready handshake",
    }

    for hi in sorted(by_hi):
        name = HIGH_BYTE_NAMES.get(hi, "?")
        ops = sorted(by_hi[hi], key=lambda x: x[0])
        lines.append(f"### `0x{hi:02x}xx` — {name}\n\n")
        lines.append("| Opcode | Dir | Name | Size min/avg/max | "
                     "Activity | Notes |\n")
        lines.append("|---|---|---|---|---|---|\n")
        for op, entries in ops:
            for d, k, e in entries:
                name_lookup = _tcp_name(op)
                size = fmt_size(e)
                cnt = fmt_count(e)
                fixed = " ✓ fixed" if fixed_size(e) else ""
                lines.append(f"| `0x{op:04x}` | {d} | {name_lookup} | "
                             f"{size}{fixed} | {cnt} | |\n")
        lines.append("\n")

    # ─── TCP request/response pairing ──────────────────────────────
    lines.append("### Request / response pairings\n\n")
    lines.append("Empirical observation: client requests in the "
                 "`0x84xx` range generally pair with server replies "
                 "in the `0x83xx` range, with a related low-byte "
                 "structure.\n\n")
    lines.append("| C→S request | Body sz | S→C reply | Body sz | Pairing |\n")
    lines.append("|---|---|---|---|---|\n")
    pair_known = [
        (0x8480, 0x8381, "Auth → AuthAck"),
        (0x8482, 0x8385, "GetCharList → CharList"),
        (0x8482, 0x8386, "Char-create commit → ack (`0x8482` reused with discriminator body)"),
        (0x8482, 0x8383, "Phase-1 GetCharList → InfoServer reply"),
        (0x8737, 0x873a, "GetGamedata → Gamedata"),
        (0x8000, 0x8001, "HandshakeB ← HandshakeA (same family)"),
        (0x8000, 0x8003, "HandshakeB → HandshakeC (same family)"),
        (0xa003, 0xa001, "SessionReady-C → SessionReady-S"),
        (0x8301, 0x8305, "AuthB → UDPServerData"),
    ]
    for c, s, descr in pair_known:
        c_keys = [k for k in packets if "TCP C->S" in k and f"0x{c:04x}" in k]
        s_keys = [k for k in packets if "TCP S->C" in k and f"0x{s:04x}" in k]
        c_size = fmt_size(packets[c_keys[0]]) if c_keys else "—"
        s_size = fmt_size(packets[s_keys[0]]) if s_keys else "—"
        lines.append(f"| `0x{c:04x}` | {c_size} | `0x{s:04x}` | "
                     f"{s_size} | {descr} |\n")
    lines.append("\n")

    # ─── UDP raw-outer ──────────────────────────────────────────────
    lines.append("## UDP raw-outer opcode space\n\n")
    lines.append("UDP outer opcodes are **single bytes**. The opcode "
                 "space is organized by 16-byte ranges with each "
                 "range mapping roughly to a subsystem. Two distinct "
                 "channels share the same opcode numbers:\n\n")
    lines.append("- **Raw outer** — used for unreliable / "
                 "low-frequency / connection-level packets and for "
                 "the high-volume entity stream.\n")
    lines.append("- **Reliable sub** — used after the `0x03` wrapper "
                 "and the same opcode value is reused with the same "
                 "semantic meaning where applicable.\n\n")

    UDP_RANGE_NAMES = {
        (0x00, 0x0f): "Connection / low-level (handshake, ping, sync, multipart-wrappers)",
        (0x10, 0x1f): "Entity & state stream (PosUpdate, GamePackets)",
        (0x20, 0x2f): "World events (Movement, NPCData, Weather, Zoning)",
        (0x30, 0x3f): "Player-info / metadata / inventory",
        (0x40, 0x6f): "(sparse) — runtime / gamedata reload",
        (0x70, 0xff): "Cipher-handshake echoes & rare events",
    }

    lines.append("### Raw-outer + reliable-sub side by side\n\n")
    lines.append("Observed opcodes shown with both their raw and "
                 "reliable forms when both exist. The convention "
                 "where both exist: same opcode number = same "
                 "semantic meaning, just chose-your-reliability.\n\n")
    lines.append("| Op | Range | Raw C→S | Raw S→C | `0x03/op` C→S | "
                 "`0x03/op` S→C | Likely role |\n")
    lines.append("|---|---|---|---|---|---|---|\n")

    all_ops = sorted(set(raw.keys()) | set(reliable.keys()))
    for op in all_ops:
        rng = next((n for r, n in UDP_RANGE_NAMES.items()
                    if r[0] <= op <= r[1]), "?")
        raw_c = "·"
        raw_s = "·"
        rel_c = "·"
        rel_s = "·"
        if op in raw:
            if "C->S" in raw[op]:
                _, e = raw[op]["C->S"]
                raw_c = fmt_size(e)
            if "S->C" in raw[op]:
                _, e = raw[op]["S->C"]
                raw_s = fmt_size(e)
        if op in reliable:
            if "C->S" in reliable[op]:
                _, e = reliable[op]["C->S"]
                rel_c = fmt_size(e)
            if "S->C" in reliable[op]:
                _, e = reliable[op]["S->C"]
                rel_s = fmt_size(e)
        role = _udp_name(op)
        lines.append(f"| `0x{op:02x}` | {rng[:30]} | {raw_c} | {raw_s} "
                     f"| {rel_c} | {rel_s} | {role} |\n")
    lines.append("\n")

    # ─── Raw vs reliable equivalence verification ───────────────────
    lines.append("### Raw vs reliable equivalence verification\n\n")
    lines.append("**Hypothesis:** for any opcode N, raw `0xN` and "
                 "reliable `0x03/0xN` carry the same logical content "
                 "— the only difference is whether the server "
                 "expects an ack. Verifying by sample comparison:\n\n")

    overlap = sorted(set(raw.keys()) & set(reliable.keys()))
    lines.append(f"Opcodes appearing in BOTH raw and reliable forms: "
                 f"**{len(overlap)}** ({', '.join(f'0x{x:02x}' for x in overlap)})\n\n")
    lines.append("| Op | Raw sample (S→C) | Reliable sample (S→C) | Same body shape? |\n")
    lines.append("|---|---|---|---|\n")
    for op in overlap:
        raw_s = ""; rel_s = ""
        if op in raw and "S->C" in raw[op]:
            samples = raw[op]["S->C"][1].get("samples", [])
            raw_s = samples[0][:32] if samples else "—"
        if op in reliable and "S->C" in reliable[op]:
            samples = reliable[op]["S->C"][1].get("samples", [])
            rel_s = samples[0][:32] if samples else "—"
        match = "(see body bytes — manual check)"
        lines.append(f"| `0x{op:02x}` | `{raw_s}` | `{rel_s}` | {match} |\n")
    lines.append("\n")

    # ─── Multipart discriminators ──────────────────────────────────
    if multipart:
        lines.append("## Multipart `0x03/0x07/disc` discriminator space\n\n")
        lines.append("Multipart logical packets are routed by the "
                     "`disc` byte (offset 6 in per-fragment header). "
                     "Same convention as raw vs reliable: each `disc` "
                     "value is its own logical packet type.\n\n")
        lines.append("| disc | Dir | Logical type | Body sz | Activity |\n")
        lines.append("|---|---|---|---|---|\n")
        for disc in sorted(multipart):
            for d, (k, e) in multipart[disc].items():
                role = _multipart_disc_name(disc)
                lines.append(f"| `0x{disc:02x}` | {d} | {role} | "
                             f"{fmt_size(e)} | {fmt_count(e)} |\n")
        lines.append("\n")

    # ─── Fixed-size opcodes (likely "control" packets) ─────────────
    lines.append("## Fixed-size opcodes (control / heartbeat packets)\n\n")
    lines.append("Opcodes where every observation has the EXACT same "
                 "size are typically heartbeats, acks, or single-"
                 "purpose control messages. Variable-size opcodes "
                 "carry payload data.\n\n")
    lines.append("| Opcode | Dir | Size | Count | Likely role |\n")
    lines.append("|---|---|---:|---:|---|\n")
    fixed = []
    for k, e in packets.items():
        if fixed_size(e) and e["count"] >= 5:
            fixed.append((k, e))
    fixed.sort(key=lambda x: -x[1]["count"])
    for k, e in fixed[:30]:
        t, d, nums = parse_key(k)
        op_str = "/".join(f"0x{n:0{4 if t == 'TCP' else 2}x}" for n in nums)
        role_lookup = (_tcp_name(nums[0]) if t == "TCP"
                       else _udp_name(nums[-1]))
        lines.append(f"| `{op_str}` | {d} | {e['size_min']}B | "
                     f"{e['count']} | {role_lookup} |\n")
    lines.append("\n")

    # ─── Predicted opcode map ──────────────────────────────────────
    lines.append("## Predicted opcode-space map\n\n")
    lines.append("Based on the structural rules above, here is what "
                 "each opcode range probably contains, including "
                 "**predicted opcodes we haven't yet observed** "
                 "(future capture targets).\n\n")
    lines.append(_predicted_map(raw, reliable))

    out_path.write_text("".join(lines))
    return out_path


# ─── Helpers: name lookups ────────────────────────────────────────────

def _tcp_name(op):
    return {
        0x8000: "HandshakeB (C→S hello)",
        0x8001: "HandshakeA (S→C hello)",
        0x8003: "HandshakeC (S→C ready)",
        0x8301: "AuthB (per-character auth)",
        0x8305: "UDPServerData",
        0x830c: "Location (zone change)",
        0x830d: "GameinfoReady",
        0x8317: "? (rare)",
        0x8381: "AuthAck",
        0x8383: "InfoServer reply / server-list entry",
        0x8385: "CharList",
        0x8386: "Char-create ack (NEW from CREATION_LEVELING_LONG)",
        0x838f: "Interaction-state marker",
        0x8480: "Auth (account)",
        0x8482: "GetCharList / CharCreate (discriminator-based)",
        0x8737: "GetGamedata",
        0x873a: "Gamedata",
        0x873c: "GetUDPConnection (no-op on retail)",
        0xa001: "SessionReady-S (server)",
        0xa002: "Session ack? (S→C, fires on interactions)",
        0xa003: "SessionReady-C (client)",
    }.get(op, "?")


def _udp_name(op):
    return {
        0x00: "inventory channel (12B fixed `0x00 0x3c …`)",
        0x01: "UDP-handshake start (C→S 10B) / inventory-slot probe (3B)",
        0x02: "inventory ack (S→C variable TLV)",
        0x03: "RELIABLE WRAPPER (always followed by sub-opcode)",
        0x04: "UDP-handshake reply (S→C 7B)",
        0x05: "?",
        0x06: "?",
        0x07: "MULTIPART WRAPPER (subordinate to 0x03/0x07 only)",
        0x08: "DISCONNECT (1B from client)",
        0x09: "?",
        0x0b: "CPing (heartbeat)",
        0x0c: "TimeSync (C→S)",
        0x0d: "?",
        0x0f: "?",
        0x11: "?",
        0x13: "GAMEDATA WRAPPER (counter + sub-packets)",
        0x1b: "Entity position broadcast (S→C 19B)",
        0x1d: "?",
        0x1f: "GamePackets / pool-status (S→C variable)",
        0x20: "Movement (bidirectional, type-bitfield-gated)",
        0x22: "CharInfo zoning sub-opcodes (only as 0x03/0x22)",
        0x23: "InfoResponse (only as 0x03/0x23)",
        0x24: "?",
        0x25: "PlayerInfo (only as 0x03/0x25)",
        0x26: "RemoveWorldItem (only as 0x03/0x26)",
        0x27: "RequestWorldInfo / WorldInfo response",
        0x28: "WorldInfo (only as 0x03/0x28)",
        0x2a: "RequestPos",
        0x2b: "CityCom DCB RPC (only as 0x03/0x2b)",
        0x2c: "StartPos / single-packet CharInfo (only as 0x03/0x2c)",
        0x2d: "NPCData (mob/entity behavior tick) — also raw 0x2d trade",
        0x2e: "Weather (only as 0x03/0x2e)",
        0x2f: "UpdateModel (only as 0x03/0x2f)",
        0x30: "ShortPlayerInfo (only as 0x03/0x30)",
        0x31: "RequestShortPlayer / ?",
        0x32: "NPC dialogue / vendor",
        0x33: "?",
        0x3a: "?",
        0x3c: "inventory-detail metadata",
        0x3e: "?",
        0x44: "?",
        0x45: "?",
    }.get(op, "?")


def _multipart_disc_name(disc):
    return {
        0x01: "CharInfo (login-time)",
        0x02: "CharsysInfo",
        0x03: "? (only seen in CREATION_LEVELING_LONG)",
        0x04: "? (only seen in CREATION_LEVELING_LONG)",
        0x38: "? (only seen in PLAZA_TO_PEPPER cross-district)",
    }.get(disc, "?")


def _predicted_map(raw, reliable):
    """Generate a predicted opcode map showing observed + gap rows."""
    lines = []
    lines.append("### Connection / low-level (`0x00` – `0x0f`)\n\n")
    lines.append("These are the smallest-numbered opcodes — typical "
                 "convention: the lowest ranges hold the most "
                 "fundamental connection-level packets, which is what "
                 "we observe.\n\n")
    lines.append("| Op | Observed | Hypothesis |\n|---|---|---|\n")
    for op in range(0x00, 0x10):
        observed = "✓" if (op in raw or op in reliable) else "·"
        hint = _udp_name(op)
        lines.append(f"| `0x{op:02x}` | {observed} | {hint} |\n")
    lines.append("\n")

    lines.append("### Entity & state stream (`0x10` – `0x1f`)\n\n")
    lines.append("| Op | Observed | Hypothesis |\n|---|---|---|\n")
    for op in range(0x10, 0x20):
        observed = "✓" if (op in raw or op in reliable) else "·"
        hint = _udp_name(op)
        lines.append(f"| `0x{op:02x}` | {observed} | {hint} |\n")
    lines.append("\n")

    lines.append("### World events (`0x20` – `0x2f`)\n\n")
    lines.append("| Op | Observed | Hypothesis |\n|---|---|---|\n")
    for op in range(0x20, 0x30):
        observed = "✓" if (op in raw or op in reliable) else "·"
        hint = _udp_name(op)
        lines.append(f"| `0x{op:02x}` | {observed} | {hint} |\n")
    lines.append("\n")

    lines.append("### Player-info / metadata (`0x30` – `0x3f`)\n\n")
    lines.append("| Op | Observed | Hypothesis |\n|---|---|---|\n")
    for op in range(0x30, 0x40):
        observed = "✓" if (op in raw or op in reliable) else "·"
        hint = _udp_name(op)
        lines.append(f"| `0x{op:02x}` | {observed} | {hint} |\n")
    lines.append("\n")

    lines.append("### Sparse upper range (`0x40` – `0xff`)\n\n")
    lines.append("Only sporadic opcodes observed. Most are "
                 "single-occurrence echoes from the cipher seed in "
                 "the very first UDP packet of the session (where "
                 "the LFSR state hasn't stabilized yet) rather than "
                 "real protocol packets.\n\n")
    lines.append("| Op | Observed | Hypothesis |\n|---|---|---|\n")
    upper_observed = sorted(op for op in (set(raw) | set(reliable))
                            if op >= 0x40)
    for op in upper_observed:
        hint = _udp_name(op)
        lines.append(f"| `0x{op:02x}` | ✓ | {hint or '? — likely cipher echo'} |\n")
    lines.append("\n")

    return "".join(lines)


def main():
    data = load_data()
    captures = data.get("captures", [])
    packets = data.get("packets", {})
    out = Path("docs/protocol/OPCODE_STRUCTURE.md")
    write_report(packets, captures, out)
    print(f"wrote {out}")
    print(f"  {len(packets)} packet types analyzed")
    print(f"  {len(captures)} captures referenced")


if __name__ == "__main__":
    main()
