#!/usr/bin/env python3
"""subtag_analysis.py — sub-tag distribution inside `0x03/0x1f`
GamePackets and a few other sub-tagged channels.

The `0x03/0x1f` body has the form `01 00 [tag] [data]` for short
state events, and `01 00 25 13 [txn LE2] [sub_tag] [data]` for
state-with-transaction events. This script walks every observed
`0x03/0x1f` body across all captures and emits a sub-tag
frequency table with marker correlation.

Output: docs/protocol/SUBTAGS.md
"""
from __future__ import annotations
import sys, datetime
from pathlib import Path
from collections import defaultdict, Counter

sys.path.insert(0, str(Path(__file__).parent))
from importlib import import_module
decrypt_mod = import_module("decrypt-retail")
burst_mod = import_module("parse-burst")
catalog = import_module("catalog_extract")

try:
    from scapy.all import PcapReader, IP, UDP, TCP
except ImportError:
    sys.exit("scapy missing")


def parse_markers(p):
    return catalog.parse_markers(p)


def walk_pcap(pcap):
    server_ip = catalog.find_server_ip(pcap)
    if not server_ip: return None, [], []
    markers_path = pcap.with_suffix(".markers")
    markers_tod = parse_markers(markers_path)
    capture_start = None
    capture_start_tod = None
    events = []  # (rel_ts, dir, key, sub_tag, sub_tag2, body)
    with PcapReader(str(pcap)) as pr:
        for pkt in pr:
            if IP not in pkt: continue
            ts = float(pkt.time)
            if capture_start is None:
                capture_start = ts
                dt = datetime.datetime.fromtimestamp(ts)
                capture_start_tod = (dt.hour * 3600 + dt.minute * 60
                                     + dt.second + dt.microsecond / 1e6)
            rel_ts = ts - capture_start
            if pkt[IP].src == server_ip: direction = "S->C"
            elif pkt[IP].dst == server_ip: direction = "C->S"
            else: continue
            if UDP not in pkt: continue
            payload = bytes(pkt[UDP].payload)
            if not payload: continue
            r = decrypt_mod.decrypt_wire_packet(payload)
            if not r: continue
            plain = r[0]
            parsed = burst_mod.parse_gamedata(plain)
            if not parsed: continue
            for sub in parsed["subs"]:
                outer = sub["outer"]
                rt = sub.get("reliable_type")
                inner = (sub.get("inner_data") if rt is not None
                         else sub.get("data", b""))
                if outer != 0x03 or rt != 0x1f: continue
                if len(inner) < 3: continue
                # Body shape: "01 00 [tag] [tag2]?? [...]"
                tag = inner[2]
                tag2 = inner[3] if len(inner) >= 4 else None
                events.append({
                    "ts": rel_ts, "dir": direction,
                    "tag": tag, "tag2": tag2,
                    "size": len(inner), "body": inner[:32].hex(),
                })

    markers_rel = []
    if capture_start_tod is not None and markers_tod:
        for mtod, label in markers_tod:
            rel = mtod - capture_start_tod
            if rel < -3600: rel += 24 * 3600
            markers_rel.append((rel, label))
    return server_ip, events, markers_rel


def main():
    pcaps = sorted(Path("strace").glob("*.pcap"))
    pcaps = [p for p in pcaps if "CERESJ" not in p.name.upper()]

    # Aggregate sub-tag frequencies across all captures
    by_tag = defaultdict(lambda: {
        "count": 0, "by_dir": Counter(), "sizes": [],
        "samples": [], "captures": Counter(), "markers": Counter(),
        "tag2_dist": Counter(),
    })

    print(f"Walking {len(pcaps)} captures...", file=sys.stderr)
    for pcap in pcaps:
        print(f"  · {pcap.name}", file=sys.stderr)
        server_ip, events, markers = walk_pcap(pcap)
        if not events: continue
        # Correlate markers
        for e in events:
            tag = e["tag"]
            entry = by_tag[tag]
            entry["count"] += 1
            entry["by_dir"][e["dir"]] += 1
            entry["sizes"].append(e["size"])
            entry["captures"][pcap.name] += 1
            if len(entry["samples"]) < 5:
                entry["samples"].append(f"{e['dir']} sz={e['size']} `{e['body']}`")
            if e["tag2"] is not None:
                entry["tag2_dist"][e["tag2"]] += 1
            for mts, mlabel in markers:
                if abs(mts - e["ts"]) <= 2.0:
                    entry["markers"][mlabel] += 1

    # Output
    lines = []
    lines.append("# `0x03/0x1f` GamePackets — Sub-tag Catalog\n\n")
    lines.append(f"_Auto-generated by `tools/subtag_analysis.py` on "
                 f"{datetime.date.today().isoformat()}._\n\n")
    lines.append("`UDP * 0x03/0x1f` is the protocol's general-purpose "
                 "state-event channel. Its body has the form "
                 "`01 00 [tag] [data...]` for short events, and "
                 "`01 00 25 [sub_tag] [tail]` for transactional events "
                 "where `sub_tag = 0x13` introduces a transaction-id "
                 "wrapped form.\n\n")
    lines.append(f"Across {len(pcaps)} retail captures, "
                 f"**{sum(e['count'] for e in by_tag.values()):,}** "
                 f"`0x03/0x1f` packets were observed with "
                 f"**{len(by_tag)}** distinct primary tag bytes.\n\n")

    TAG_NAMES = {
        0x22: "world-info ack",
        0x25: "state-update transaction (sub-tag follows)",
        0x3d: "in-flight ack burst (set { 11 } observed during fall)",
        0x3e: "?",
        0x4c: "combat-readiness heartbeat (10s cadence)",
        0x17: "(combined with sub-tag 0x25/0x13 → use-object)",
    }

    # Sub-tag table (tag = 0x25 has rich sub-tag space)
    lines.append("## Primary tag distribution\n\n")
    lines.append("| Tag | Count | Dir distribution | Size min/avg/max | "
                 "Top tag2 (next byte) | Top markers (within ±2s) | Likely role |\n")
    lines.append("|---|---:|---|---|---|---|---|\n")
    for tag in sorted(by_tag, key=lambda t: -by_tag[t]["count"]):
        e = by_tag[tag]
        sizes = e["sizes"]
        sz_str = (f"{min(sizes)}/{sum(sizes) // len(sizes)}/{max(sizes)}"
                  if sizes else "—")
        dir_str = "/".join(f"{d}:{n}" for d, n in e["by_dir"].most_common())
        tag2_str = ", ".join(f"`0x{t:02x}`×{n}" for t, n in
                              e["tag2_dist"].most_common(5)) or "—"
        markers_str = ", ".join(f"{l}({n})"
                                for l, n in e["markers"].most_common(3)) or "—"
        role = TAG_NAMES.get(tag, "?")
        lines.append(f"| `0x{tag:02x}` | {e['count']} | {dir_str} | "
                     f"{sz_str} | {tag2_str} | {markers_str} | {role} |\n")
    lines.append("\n")

    # ─── Tag 0x25 sub-tag deep dive ────────────────────────────────
    lines.append("## Tag `0x25` — state-update transactions\n\n")
    lines.append("Tag `0x25` is the most populated tag and carries "
                 "transactional state updates wrapped as "
                 "`01 00 25 [sub_tag] [...]`. Documented sub-tags from "
                 "memory + flow analysis:\n\n")
    lines.append("| sub-tag | Role | Verified by |\n|---|---|---|\n")
    SUB_25_KNOWN = {
        0x04: ("Skill-point spend (C→S 8B body) / cash (S→C 13B/41B body)",
               "level_up.md, vendor_buy.md, combat_kill_npc.md"),
        0x13: ("Transactional wrapper: 01 00 25 13 [txn LE2] [tag] [data]",
               "cash_and_falldamage_subops memory"),
        0x1f: ("Pool-status burst (HP/PSI/STA + status flag, 14B body) — "
               "ALSO used as `0x1f` raw outer for foreign entities",
               "death_respawn.md, fall_damage.md"),
        0x23: ("Tick heartbeat — body `010025 23 [byte]` where byte counts "
               "monotonically — appears as 5B `01 00 25 23 NN`",
               "every capture, ~0.4 Hz cadence"),
        0x32: ("Recurring heartbeat variant",
               "ZONING_AND_ITEMS_LONG, CASH_VENDOR captures"),
    }
    for sub, (role, where) in sorted(SUB_25_KNOWN.items()):
        lines.append(f"| `0x{sub:02x}` | {role} | {where} |\n")
    lines.append("\n")

    # ─── Tag 0x3d sub-tag map ──────────────────────────────────────
    lines.append("## Tag `0x3d` — in-flight / loading filler\n\n")
    lines.append("Tag `0x3d` C→S body: `01 00 3d 11 00 00 00 00` "
                 "(8 bytes, fixed). Bursts during:\n\n")
    lines.append("- Falling (verified — `cash_and_falldamage_subops` memory)\n")
    lines.append("- BSP loading after Zoning2 (zone-walk filler stream)\n\n")
    lines.append("This tag effectively means **\"client is in a "
                 "high-update state and is acknowledging at high "
                 "rate\"**. The body is data-free; it's a pure "
                 "ack-pulse marker.\n\n")

    # ─── Tag 0x4c heartbeat ────────────────────────────────────────
    lines.append("## Tag `0x4c` — combat-readiness heartbeat\n\n")
    lines.append("Tag `0x4c` C→S body: `01 00 4c 0f 00 03 00` (7B). "
                 "Fires at exactly **10-second intervals** in combat "
                 "captures (verified in AUGUSTO at t=26.42, 36.14, "
                 "46.13, 56.23, …). Likely a 'I am alive and ready "
                 "to receive combat events' heartbeat that the "
                 "server uses to time out players who lose connection "
                 "mid-combat.\n\n")

    out_path = Path("docs/protocol/SUBTAGS.md")
    out_path.write_text("".join(lines))
    print(f"\nwrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
