// ObfuscateStreamBuf Decompilation
// Generated by Ghidra headless analysis

// Vtable: ObfuscateStreamBuf::vftable at 00a1fd1c

// vtable[0] = thunk_FUN_004dff30 at 0x405a65
// (thunk to FUN_004dff30 at 004dff30)
// === FUN_004dff30 at 004dff30 ===

basic_streambuf<char,struct_std::char_traits<char>_> * __thiscall
FUN_004dff30(basic_streambuf<char,struct_std::char_traits<char>_> *param_1,byte param_2)

{
  std::basic_streambuf<char,struct_std::char_traits<char>_>::
  ~basic_streambuf<char,struct_std::char_traits<char>_>(param_1);
  if ((param_2 & 1) != 0) {
    thunk_FUN_009ac142(param_1,0x44);
  }
  return param_1;
}



// vtable[1] = _Lock at 0x9abfbc
// === _Lock at 009abfbc ===

void __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::_Lock
          (basic_streambuf<char,struct_std::char_traits<char>_> *this)

{
                    /* WARNING: Could not recover jumptable at 0x009abfbc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  _Lock(this);
  return;
}



// vtable[2] = _Unlock at 0x9abfb6
// === _Unlock at 009abfb6 ===

void __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::_Unlock
          (basic_streambuf<char,struct_std::char_traits<char>_> *this)

{
                    /* WARNING: Could not recover jumptable at 0x009abfb6. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  _Unlock(this);
  return;
}



// vtable[3] = thunk_FUN_004dff90 at 0x40924b
// (thunk to FUN_004dff90 at 004dff90)
// === FUN_004dff90 at 004dff90 ===

int __thiscall FUN_004dff90(int param_1,int param_2)

{
  int *piVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  
  if (param_2 == -1) {
    return -1;
  }
  piVar1 = *(int **)(param_1 + 0x40);
  uVar3 = *(uint *)(param_1 + 0x3c);
  iVar2 = *piVar1;
  if (piVar1[3] + (((uint)(iVar2 * 0xe) >> 0x10 ^ iVar2 * 0xe) & 0xff) * -0x1020305 <= uVar3) {
    do {
      uVar3 = (uint)(iVar2 * 0xe) >> 0x10 & 0xff ^ iVar2 * 0xe & 0xffU;
      uVar4 = piVar1[3] + uVar3 * -0x1020305;
      if (uVar4 < piVar1[1] + uVar3 * -0x1020305) {
        iVar2 = (uVar4 + 1) * iVar2;
        *(byte *)(uVar4 + piVar1[2]) = (byte)((uint)iVar2 >> 0x10) ^ (byte)iVar2 ^ 0x20;
        piVar1[3] = (((uint)(*piVar1 * 0xe) >> 0x10 ^ *piVar1 * 0xe) & 0xff) * 0x1020305 + 1 + uVar4
        ;
      }
      piVar1 = *(int **)(param_1 + 0x40);
      uVar3 = *(uint *)(param_1 + 0x3c);
      iVar2 = *piVar1;
    } while (piVar1[3] + (((uint)(iVar2 * 0xe) >> 0x10 ^ iVar2 * 0xe) & 0xff) * -0x1020305 <= uVar3)
    ;
  }
  iVar2 = (uVar3 + 1) * iVar2;
  *(byte *)(uVar3 + piVar1[2]) = (byte)((uint)iVar2 >> 0x10) ^ (byte)iVar2 ^ (byte)param_2;
  *(int *)(param_1 + 0x3c) = *(int *)(param_1 + 0x3c) + 1;
  return param_2;
}



// vtable[4] = pbackfail at 0x9abfb0
// === pbackfail at 009abfb0 ===

int __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::pbackfail
          (basic_streambuf<char,struct_std::char_traits<char>_> *this,int param_1)

{
  int iVar1;
  
                    /* WARNING: Could not recover jumptable at 0x009abfb0. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar1 = pbackfail(this,param_1);
  return iVar1;
}



// vtable[5] = showmanyc at 0x9abce5
// === showmanyc at 009abce5 ===

__int64 __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::showmanyc
          (basic_streambuf<char,struct_std::char_traits<char>_> *this)

{
  __int64 _Var1;
  
                    /* WARNING: Could not recover jumptable at 0x009abce5. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  _Var1 = showmanyc(this);
  return _Var1;
}



// vtable[6] = thunk_FUN_004e02a0 at 0x41230a
// (thunk to FUN_004e02a0 at 004e02a0)
// === FUN_004e02a0 at 004e02a0 ===

uint __fastcall FUN_004e02a0(int param_1)

{
  uint uVar1;
  int *piVar2;
  uint uVar3;
  
  uVar1 = *(uint *)(param_1 + 0x38);
  piVar2 = *(int **)(param_1 + 0x40);
  uVar3 = *piVar2 * 0xe;
  if (uVar1 < piVar2[3] + ((uVar3 >> 0x10 ^ uVar3) & 0xff) * -0x1020305) {
    uVar3 = (uVar1 + 1) * *piVar2;
    return (uint)*(byte *)(piVar2[2] + uVar1) ^ uVar3 >> 0x10 & 0xff ^ uVar3 & 0xff;
  }
  return 0xffffffff;
}



// vtable[7] = thunk_FUN_004e0220 at 0x416eff
// (thunk to FUN_004e0220 at 004e0220)
// === FUN_004e0220 at 004e0220 ===

uint __fastcall FUN_004e0220(int param_1)

{
  int *piVar1;
  uint uVar2;
  uint uVar3;
  
  piVar1 = *(int **)(param_1 + 0x40);
  uVar2 = *(uint *)(param_1 + 0x38);
  if (uVar2 < piVar1[3] + (((uint)(*piVar1 * 0xe) >> 0x10 ^ *piVar1 * 0xe) & 0xff) * -0x1020305) {
    *(uint *)(param_1 + 0x38) = uVar2 + 1;
    uVar3 = *piVar1 * (uVar2 + 1);
    return (uint)*(byte *)(piVar1[2] + uVar2) ^ uVar3 >> 0x10 & 0xff ^ uVar3 & 0xff;
  }
  return 0xffffffff;
}



// vtable[8] = xsgetn at 0x9abef0
// === xsgetn at 009abef0 ===

__int64 __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::xsgetn
          (basic_streambuf<char,struct_std::char_traits<char>_> *this,char *param_1,__int64 param_2)

{
  __int64 _Var1;
  
                    /* WARNING: Could not recover jumptable at 0x009abef0. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  _Var1 = xsgetn(this,param_1,param_2);
  return _Var1;
}



// vtable[9] = xsputn at 0x9abef6
// === xsputn at 009abef6 ===

__int64 __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::xsputn
          (basic_streambuf<char,struct_std::char_traits<char>_> *this,char *param_1,__int64 param_2)

{
  __int64 _Var1;
  
                    /* WARNING: Could not recover jumptable at 0x009abef6. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  _Var1 = xsputn(this,param_1,param_2);
  return _Var1;
}



// vtable[10] = thunk_FUN_004e00e0 at 0x40fd6c
// (thunk to FUN_004e00e0 at 004e00e0)
// === FUN_004e00e0 at 004e00e0 ===

void __thiscall
FUN_004e00e0(int param_1,int *param_2,int param_3,undefined4 param_4,int param_5,uint param_6)

{
  uint uVar1;
  
  if ((param_6 & 1) != 0) {
    if (param_5 == 0) {
      *(int *)(param_1 + 0x38) = param_3;
    }
    else if (param_5 == 1) {
      *(int *)(param_1 + 0x38) = *(int *)(param_1 + 0x38) + param_3;
    }
    else if (param_5 == 2) {
      uVar1 = **(int **)(param_1 + 0x40) * 0xe;
      *(uint *)(param_1 + 0x38) =
           (*(int **)(param_1 + 0x40))[3] + ((uVar1 >> 0x10 ^ uVar1) & 0xff) * -0x1020305 + param_3;
    }
  }
  if ((param_6 & 2) == 0) {
    param_3 = *(int *)(param_1 + 0x38);
    goto LAB_004e0191;
  }
  if (param_5 == 0) {
    *(int *)(param_1 + 0x3c) = param_3;
  }
  else {
    if (param_5 == 1) {
      *(int *)(param_1 + 0x3c) = *(int *)(param_1 + 0x3c) + param_3;
      param_3 = *(int *)(param_1 + 0x3c);
      goto LAB_004e0191;
    }
    if (param_5 == 2) {
      uVar1 = **(int **)(param_1 + 0x40) * 0xe;
      param_3 = (*(int **)(param_1 + 0x40))[3] + ((uVar1 >> 0x10 ^ uVar1) & 0xff) * -0x1020305 +
                param_3;
      *(int *)(param_1 + 0x3c) = param_3;
      goto LAB_004e0191;
    }
  }
  param_3 = *(int *)(param_1 + 0x3c);
LAB_004e0191:
  *param_2 = param_3;
  param_2[1] = 0;
  param_2[2] = 0;
  param_2[3] = 0;
  param_2[4] = 0;
  param_2[5] = 0;
  return;
}



// vtable[11] = thunk_FUN_004e01f0 at 0x40f619
// (thunk to FUN_004e01f0 at 004e01f0)
// === FUN_004e01f0 at 004e01f0 ===

undefined4 __thiscall
FUN_004e01f0(int *param_1,undefined4 param_2,uint param_3,int param_4,uint param_5,int param_6,
            undefined4 param_7,undefined4 param_8,undefined4 param_9)

{
  (**(code **)(*param_1 + 0x28))
            (param_2,param_5 + param_3,param_6 + param_4 + (uint)CARRY4(param_5,param_3),0,param_9);
  return param_2;
}



// vtable[12] = setbuf at 0x9abfa4
// === setbuf at 009abfa4 ===

basic_streambuf<char,struct_std::char_traits<char>_> * __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::setbuf
          (basic_streambuf<char,struct_std::char_traits<char>_> *this,char *param_1,__int64 param_2)

{
  basic_streambuf<char,struct_std::char_traits<char>_> *pbVar1;
  
                    /* WARNING: Could not recover jumptable at 0x009abfa4. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  pbVar1 = setbuf(this,param_1,param_2);
  return pbVar1;
}



// vtable[13] = sync at 0x9abfc2
// === sync at 009abfc2 ===

int __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::sync
          (basic_streambuf<char,struct_std::char_traits<char>_> *this)

{
  int iVar1;
  
                    /* WARNING: Could not recover jumptable at 0x009abfc2. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar1 = sync(this);
  return iVar1;
}



// vtable[14] = imbue at 0x9abf9e
// === imbue at 009abf9e ===

void __thiscall
std::basic_streambuf<char,struct_std::char_traits<char>_>::imbue
          (basic_streambuf<char,struct_std::char_traits<char>_> *this,locale *param_1)

{
                    /* WARNING: Could not recover jumptable at 0x009abf9e. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  imbue(this,param_1);
  return;
}



// ============ Constructor ============
// === FUN_004dfd80 at 004dfd80 ===

undefined1 * __fastcall FUN_004dfd80(undefined1 *param_1)

{
  basic_streambuf<char,struct_std::char_traits<char>_> *this;
  basic_ostream<char,struct_std::char_traits<char>_> *this_00;
  char cVar1;
  int iVar2;
  void *local_10;
  undefined1 *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &LAB_009c440a;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  this = (basic_streambuf<char,struct_std::char_traits<char>_> *)(param_1 + 4);
  *param_1 = 0;
  std::basic_streambuf<char,struct_std::char_traits<char>_>::
  basic_streambuf<char,struct_std::char_traits<char>_>(this);
  *(undefined ***)this = ObfuscateStreamBuf::vftable;
  *(undefined4 *)(param_1 + 0x3c) = 0;
  *(undefined4 *)(param_1 + 0x40) = 0;
  *(int **)(param_1 + 0x44) = &DAT_00b05360;
  this_00 = (basic_ostream<char,struct_std::char_traits<char>_> *)(param_1 + 0x48);
  local_8 = 0;
  std::basic_ostream<char,struct_std::char_traits<char>_>::
  basic_ostream<char,struct_std::char_traits<char>_>(this_00,this,false);
  local_8._0_1_ = 1;
  thunk_FUN_00456cf0(0,&DAT_00a0af83);
  local_8 = CONCAT31(local_8._1_3_,2);
  DAT_00b0536c = (((uint)(DAT_00b05360 * 0xe) >> 0x10 ^ DAT_00b05360 * 0xe) & 0xff) * 0x1020305;
  std::basic_ostream<char,struct_std::char_traits<char>_>::seekp(this_00,0,0,0,0,0);
  std::basic_ostream<char,struct_std::char_traits<char>_>::operator<<
            (this_00,(_func_ios_base_ptr_ios_base_ptr *)&LAB_00411c7f);
  cVar1 = thunk_FUN_00458490();
  if (cVar1 != '\0') {
    iVar2 = thunk_FUN_00457c20(0,0xf);
    if (iVar2 != 0) {
      *param_1 = 1;
      ExceptionList = local_10;
      return param_1;
    }
  }
  thunk_FUN_004466a0(this_00,&DAT_00a1fd64);
  ExceptionList = local_10;
  return param_1;
}



// ============ FUN_00586770 (called for byte 0x80) ============
// === FUN_00586770 at 00586770 ===

short FUN_00586770(int param_1)

{
  byte bVar1;
  byte *pbVar2;
  byte bVar3;
  
  pbVar2 = *(byte **)(param_1 + 0xac);
  if (pbVar2 < *(byte **)(param_1 + 0xb0)) {
    bVar3 = *pbVar2;
    pbVar2 = pbVar2 + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  else if (*(int *)(param_1 + 0x20) == 0) {
    bVar3 = 0;
  }
  else {
    FUN_005919a0(param_1);
    bVar3 = **(byte **)(param_1 + 0xac);
    pbVar2 = *(byte **)(param_1 + 0xac) + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  if (*(byte **)(param_1 + 0xb0) <= pbVar2) {
    if (*(int *)(param_1 + 0x20) == 0) {
      return (ushort)bVar3 * 0x100;
    }
    FUN_005919a0(param_1);
    pbVar2 = *(byte **)(param_1 + 0xac);
  }
  bVar1 = *pbVar2;
  *(byte **)(param_1 + 0xac) = pbVar2 + 1;
  return CONCAT11(bVar3,bVar1);
}



// ============ FUN_005918a0 (processing loop) ============
// === FUN_005918a0 at 005918a0 ===

int FUN_005918a0(int param_1,uint param_2,int param_3)

{
  undefined1 uVar1;
  undefined1 *puVar2;
  int iVar3;
  uint uVar4;
  int iVar5;
  
  uVar4 = 0x80;
  iVar5 = 0;
  do {
    if ((param_2 & uVar4) != 0) {
      if (*(int *)(param_1 + 0x10) == 0) {
LAB_005918f3:
        if (*(uint *)(param_1 + 0xb0) <= *(uint *)(param_1 + 0xac)) {
LAB_005918dc:
          FUN_00586470("bad file");
          return 0;
        }
      }
      else {
        iVar3 = (**(code **)(param_1 + 0x18))(*(undefined4 *)(param_1 + 0x1c));
        if (iVar3 != 0) {
          if (*(int *)(param_1 + 0x20) == 0) goto LAB_005918dc;
          goto LAB_005918f3;
        }
      }
      puVar2 = *(undefined1 **)(param_1 + 0xac);
      if (puVar2 < *(undefined1 **)(param_1 + 0xb0)) {
        uVar1 = *puVar2;
        *(undefined1 **)(param_1 + 0xac) = puVar2 + 1;
        *(undefined1 *)(iVar5 + param_3) = uVar1;
      }
      else if (*(int *)(param_1 + 0x20) == 0) {
        *(undefined1 *)(iVar5 + param_3) = 0;
      }
      else {
        FUN_005919a0(param_1);
        uVar1 = **(undefined1 **)(param_1 + 0xac);
        *(undefined1 **)(param_1 + 0xac) = *(undefined1 **)(param_1 + 0xac) + 1;
        *(undefined1 *)(iVar5 + param_3) = uVar1;
      }
    }
    iVar5 = iVar5 + 1;
    uVar4 = (int)uVar4 >> 1;
    if (3 < iVar5) {
      return param_3;
    }
  } while( true );
}



// ============ FUN_00584710 (inner loop) ============
// === FUN_00584710 at 00584710 ===

void FUN_00584710(byte param_1,undefined1 *param_2,undefined1 *param_3)

{
  if ((char)param_1 < '\0') {
    *param_2 = *param_3;
  }
  if ((param_1 & 0x40) != 0) {
    param_2[1] = param_3[1];
  }
  if ((param_1 & 0x20) != 0) {
    param_2[2] = param_3[2];
  }
  if ((param_1 & 0x10) != 0) {
    param_2[3] = param_3[3];
  }
  return;
}



// ============ Function containing SUB EBX,0x7F (0x58e920 area) ============
// === FUN_0058e710 at 0058e710 ===

/* WARNING: Function: __security_check_cookie replaced with injection: security_check_cookie */

uint FUN_0058e710(int param_1,uint param_2,int param_3,int *param_4,uint param_5)

{
  uint uVar1;
  byte *pbVar2;
  int iVar3;
  uint uVar4;
  byte bVar5;
  short sVar6;
  undefined3 uVar9;
  int iVar7;
  uint uVar8;
  uint uVar10;
  char *pcVar11;
  undefined1 local_5c [4];
  undefined1 local_58 [4];
  uint local_54;
  int local_50;
  char *local_4c;
  int *local_48;
  uint local_44;
  byte *local_40;
  uint local_3c;
  uint local_38;
  int local_34;
  uint local_30;
  uint local_2c;
  char local_28 [2];
  byte local_26 [30];
  uint local_8;
  
  local_8 = DAT_00b13e00 ^ (uint)&stack0xfffffffc;
  local_44 = param_2;
  local_48 = param_4;
  local_54 = param_5;
  local_30 = 0;
  local_50 = param_1;
  pcVar11 = local_28;
  iVar3 = 0;
LAB_0058e745:
  if (iVar3 == 10) goto LAB_0058ebc8;
  local_34 = iVar3 + 1;
  local_4c = pcVar11 + 3;
  pbVar2 = *(byte **)(param_1 + 0xac);
  if (pbVar2 < *(byte **)(param_1 + 0xb0)) {
    iVar3 = (uint)*pbVar2 << 8;
    pbVar2 = pbVar2 + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  else if (*(int *)(param_1 + 0x20) == 0) {
    iVar3 = 0;
  }
  else {
    FUN_005919a0(param_1);
    iVar3 = (uint)**(byte **)(param_1 + 0xac) << 8;
    pbVar2 = *(byte **)(param_1 + 0xac) + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  uVar9 = (undefined3)((uint)iVar3 >> 8);
  if (pbVar2 < *(byte **)(param_1 + 0xb0)) {
    sVar6 = (short)CONCAT31(uVar9,*pbVar2);
    pbVar2 = pbVar2 + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  else if (*(int *)(param_1 + 0x20) == 0) {
    sVar6 = (short)((uint)iVar3 >> 8) << 8;
  }
  else {
    FUN_005919a0(param_1);
    sVar6 = (short)CONCAT31(uVar9,**(undefined1 **)(param_1 + 0xac));
    pbVar2 = *(undefined1 **)(param_1 + 0xac) + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  *pcVar11 = (char)sVar6;
  if (pbVar2 < *(byte **)(param_1 + 0xb0)) {
    bVar5 = *pbVar2;
    pbVar2 = pbVar2 + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  else if (*(int *)(param_1 + 0x20) == 0) {
    bVar5 = 0;
  }
  else {
    FUN_005919a0(param_1);
    bVar5 = **(byte **)(param_1 + 0xac);
    pbVar2 = *(byte **)(param_1 + 0xac) + 1;
    *(byte **)(param_1 + 0xac) = pbVar2;
  }
  pcVar11[1] = bVar5;
  if (pbVar2 < *(byte **)(param_1 + 0xb0)) {
    bVar5 = *pbVar2;
    *(byte **)(param_1 + 0xac) = pbVar2 + 1;
  }
  else if (*(int *)(param_1 + 0x20) == 0) {
    bVar5 = 0;
  }
  else {
    FUN_005919a0(param_1);
    bVar5 = **(byte **)(param_1 + 0xac);
    *(byte **)(param_1 + 0xac) = *(byte **)(param_1 + 0xac) + 1;
  }
  local_30 = local_30 | bVar5;
  iVar3 = *(int *)(param_1 + 0x10);
  pcVar11[2] = bVar5;
  if (iVar3 == 0) {
LAB_0058e861:
    if (*(uint *)(param_1 + 0xb0) <= *(uint *)(param_1 + 0xac)) goto LAB_0058ebc1;
  }
  else {
    iVar3 = (**(code **)(param_1 + 0x18))(*(undefined4 *)(param_1 + 0x1c));
    if (iVar3 != 0) {
      if (*(int *)(param_1 + 0x20) != 0) goto LAB_0058e861;
LAB_0058ebc1:
      pcVar11 = "bad file";
      goto LAB_0058ebcd;
    }
  }
  if ((char)sVar6 != '\b') goto LAB_0058ebc8;
  pcVar11 = local_4c;
  iVar3 = local_34;
  if ((char)((ushort)sVar6 >> 8) == '\0') {
    local_4c = (char *)0x0;
    *local_48 = ((local_30 & 0x10) != 0) + 3;
    if (0 < param_3) {
      iVar3 = local_44 * 4;
      iVar7 = local_34;
      uVar4 = local_44;
      uVar8 = local_54;
      do {
        local_48 = (int *)0x0;
        if (0 < iVar7) {
          local_40 = local_26;
          iVar3 = local_34;
          uVar10 = uVar8;
          local_30 = uVar8;
          do {
            bVar5 = local_40[-1];
            if (bVar5 == 0) {
              iVar7 = 0;
              uVar8 = local_30;
              if (0 < (int)uVar4) {
                local_3c = (uint)*local_40;
                do {
                  iVar3 = FUN_005918a0(param_1,local_3c,uVar10);
                  if (iVar3 == 0) {
                    return 0;
                  }
                  iVar7 = iVar7 + 1;
                  uVar10 = uVar10 + 4;
                  uVar4 = local_44;
                  iVar3 = local_34;
                  uVar8 = local_30;
                } while (iVar7 < (int)local_44);
              }
            }
            else {
              uVar1 = uVar4;
              uVar8 = uVar10;
              if (bVar5 == 1) {
                while (local_2c = uVar1, 0 < (int)local_2c) {
                  pbVar2 = *(byte **)(param_1 + 0xac);
                  if (pbVar2 < *(byte **)(param_1 + 0xb0)) {
                    bVar5 = *pbVar2;
                    *(byte **)(param_1 + 0xac) = pbVar2 + 1;
                  }
                  else if (*(int *)(param_1 + 0x20) == 0) {
                    bVar5 = 0;
                  }
                  else {
                    FUN_005919a0(param_1);
                    bVar5 = **(byte **)(param_1 + 0xac);
                    *(byte **)(param_1 + 0xac) = *(byte **)(param_1 + 0xac) + 1;
                  }
                  if (*(int *)(param_1 + 0x10) == 0) {
LAB_0058eaba:
                    if (*(uint *)(param_1 + 0xb0) <= *(uint *)(param_1 + 0xac)) goto LAB_0058ebc1;
                  }
                  else {
                    iVar3 = (**(code **)(param_1 + 0x18))(*(undefined4 *)(param_1 + 0x1c));
                    if (iVar3 != 0) {
                      if (*(int *)(param_1 + 0x20) != 0) goto LAB_0058eaba;
                      goto LAB_0058ebc1;
                    }
                  }
                  uVar4 = (uint)bVar5;
                  if (local_2c < bVar5) {
                    uVar4 = local_2c & 0xff;
                  }
                  local_3c = (uint)*local_40;
                  local_38 = uVar4;
                  iVar3 = FUN_005918a0(param_1,local_3c,local_5c);
                  uVar8 = local_3c;
                  if (iVar3 == 0) {
                    return 0;
                  }
                  for (; uVar4 != 0; uVar4 = uVar4 - 1) {
                    FUN_00584710(uVar8,uVar10,local_5c);
                    uVar10 = uVar10 + 4;
                    param_1 = local_50;
                  }
                  uVar4 = local_44;
                  iVar3 = local_34;
                  uVar8 = local_30;
                  uVar1 = local_2c - (local_38 & 0xff);
                }
              }
              else {
                if (bVar5 != 2) goto LAB_0058ebc8;
                while (local_2c = uVar1, 0 < (int)local_2c) {
                  pbVar2 = *(byte **)(param_1 + 0xac);
                  if (pbVar2 < *(byte **)(param_1 + 0xb0)) {
                    uVar4 = (uint)*pbVar2;
                    *(byte **)(param_1 + 0xac) = pbVar2 + 1;
                  }
                  else if (*(int *)(param_1 + 0x20) == 0) {
                    uVar4 = 0;
                  }
                  else {
                    FUN_005919a0(param_1);
                    uVar4 = (uint)**(byte **)(param_1 + 0xac);
                    *(byte **)(param_1 + 0xac) = *(byte **)(param_1 + 0xac) + 1;
                  }
                  if (*(int *)(param_1 + 0x10) == 0) {
LAB_0058e96d:
                    if (*(uint *)(param_1 + 0xb0) <= *(uint *)(param_1 + 0xac)) goto LAB_0058ebc1;
                  }
                  else {
                    iVar3 = (**(code **)(param_1 + 0x18))(*(undefined4 *)(param_1 + 0x1c));
                    if (iVar3 != 0) {
                      if (*(int *)(param_1 + 0x20) != 0) goto LAB_0058e96d;
                      goto LAB_0058ebc1;
                    }
                  }
                  if (uVar4 < 0x80) {
                    uVar8 = uVar4 + 1;
                    if (local_2c < uVar8) goto LAB_0058ebc1;
                    local_38 = 0;
                    if (uVar8 != 0) {
                      local_3c = (uint)*local_40;
                      do {
                        iVar3 = FUN_005918a0(param_1,local_3c,uVar10);
                        if (iVar3 == 0) {
                          return 0;
                        }
                        uVar10 = uVar10 + 4;
                        local_38 = local_38 + 1;
                      } while ((int)local_38 < (int)uVar8);
                    }
                  }
                  else {
                    if (uVar4 == 0x80) {
                      uVar4 = FUN_00586770(param_1);
                    }
                    else {
                      uVar4 = uVar4 - 0x7f;
                    }
                    local_38 = uVar4;
                    if ((int)local_2c < (int)uVar4) goto LAB_0058ebc1;
                    local_3c = (uint)*local_40;
                    iVar3 = FUN_005918a0(param_1,local_3c,local_58);
                    uVar1 = local_3c;
                    if (iVar3 == 0) {
                      return 0;
                    }
                    uVar8 = uVar4;
                    if (0 < (int)uVar4) {
                      do {
                        FUN_00584710(uVar1,uVar10,local_58);
                        uVar10 = uVar10 + 4;
                        uVar4 = uVar4 - 1;
                        uVar8 = local_38;
                        param_1 = local_50;
                      } while (uVar4 != 0);
                    }
                  }
                  uVar1 = local_2c - uVar8;
                  uVar4 = local_44;
                  iVar3 = local_34;
                  uVar8 = local_30;
                }
              }
            }
            local_48 = (int *)((int)local_48 + 1);
            local_40 = local_40 + 3;
            uVar10 = uVar8;
          } while ((int)local_48 < iVar3);
          iVar3 = uVar4 * 4;
          iVar7 = local_34;
        }
        local_4c = local_4c + 1;
        uVar8 = uVar8 + iVar3;
      } while ((int)local_4c < param_3);
    }
    return local_54;
  }
  goto LAB_0058e745;
LAB_0058ebc8:
  pcVar11 = "bad format";
LAB_0058ebcd:
  FUN_00586470(pcVar11);
  return 0;
}



// ============ sendto() callers ============

// Done!
